# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dmQh8UZUmEwGO8lsw7JjSb1fpaoHo8TP
"""

notesbook task1 list



# Create a list of 10 integers
numbers = [12, 47, 8, 99, 56, 71, 39, 25, 14, 82]
print('Original List:', numbers)

# Sum, max, and min
print('Sum:', sum(numbers))
print('Max:', max(numbers))
print('Min:', min(numbers))

# Add and remove element
numbers.append(60)
numbers.remove(47)
print('Updated List:', numbers)

# Sort ascending and descending
print('Ascending:', sorted(numbers))
print('Descending:', sorted(numbers, reverse=True))

"""**Tuple**"""

# Create a list of 10 integers
numbers = [15, 62, 7, 101, 48, 73, 29, 36, 19, 95]
print('Original List:', numbers)

# Sum, max, and min
print('Sum:', sum(numbers))
print('Max:', max(numbers))
print('Min:', min(numbers))

# Add and remove element
numbers.append(85)
numbers.remove(62)
print('Updated List:', numbers)

# Sort ascending and descending
print('Ascending:', sorted(numbers))
print('Descending:', sorted(numbers, reverse=True))

"""**Set **"""

# Create sets
set_a = {11, 12, 13, 14, 15}
set_b = {14, 15, 16, 17, 18}

# Union, Intersection, Difference
print('Union:', set_a | set_b)
print('Intersection:', set_a & set_b)
print('Difference:', set_a - set_b)

# Add and remove
set_a.add(20)
set_a.remove(12)
print('Updated Set A:', set_a)

# Check existence
print('Is 15 in set_a?', 15 in set_a)

"""**Dictionary**"""

# Create dictionary
students = {'Hina': 82, 'Bilal': 76, 'Nadia': 91, 'Kashif': 87, 'Ayesha': 95}

# Print keys and values
print('Keys:', students.keys())
print('Values:', students.values())

# Update value
students['Hina'] = 89
print('Updated Dictionary:', students)

# Delete a key-value pair
del students['Bilal']
print('After Deletion:', students)

# Check if key exists
print('Is Nadia in dictionary?', 'Nadia' in students)

"""Numpy"""

import numpy as np

# Create 1D array
arr = np.arange(5, 25)   # numbers from 5 to 24
print('1D Array:', arr)

# Reshape to 5x4 matrix
matrix = arr.reshape(5, 4)
print('5x4 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(25, 45)   # numbers from 25 to 44
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)

"""Matplotlib

"""

import matplotlib.pyplot as plt

# Line Plot
x = list(range(1, 11))
y = [i*3 for i in x]   # multiples of 3
plt.plot(x, y, marker='o', color='green')
plt.title('Numbers vs Multiples of 3')
plt.xlabel('Numbers')
plt.ylabel('Multiples of 3')
plt.show()

# Bar Chart
students = ['Hina', 'Bilal', 'Nadia', 'Kashif', 'Ayesha']
marks = [72, 85, 91, 67, 88]
plt.bar(students, marks, color='orange')
plt.title('Student Marks')
plt.xlab